#!/Users/kduff/.edm/envs/lnl/bin/python

import os
import sys


fname = sys.argv[1]
execute_name, _ = fname.split(".rs")

os.system("clear")
os.system(f"rustc {fname} && echo 'L&L: Build successful' && echo  && ./{execute_name} && rm ./{execute_name}")
