[package]
name = "guess_the_number"
version = "0.1.0"
authors = ["Kevin Duff <kduff@enthought.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
